StoreApp/Components/CartSummaryViewComponent.cs
using Entities.Models;
using Microsoft.AspNetCore.Mvc;

namespace StoreApp.Components;

public class CartSummaryViewComponent : ViewComponent
{
    private readonly Cart _cart;

    public CartSummaryViewComponent(Cart cartService)
    {
        _cart = cartService;
    }

    public string Invoke()
    {
        return _cart.Lines.Count.ToString();
    }
}

StoreApp/Components/ProductSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Services.Contracts;

namespace StoreApp.Components;

public class ProductSummaryViewComponent : ViewComponent
{
    private readonly IServiceManager _manager;

    public ProductSummaryViewComponent(IServiceManager manager)
    {
        _manager = manager;
    }

    public string Invoke()
    {
        var model = _manager.ProductService.GetAllProducts(false).Count().ToString();
        return model;
    }
}

StoreApp/Controllers/CategoryController.cs
using Entities.Models;
using Microsoft.AspNetCore.Mvc;
using Repositories.Contracts;
using Services.Contracts;

namespace StoreApp.Controllers
{
    public class CategoryController : Controller
    {
        private IServiceManager _manager;

        public CategoryController(IServiceManager manager)
        {
            _manager = manager;
        }

        public IActionResult Index()
        {
            var model = _manager.CategoryService.GetAllCategories(false);
            return View(model);
        }
    }
}

StoreApp/Controllers/ProductController.cs
using Entities.RequestParameters;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Repositories;
using Repositories.Contracts;
using Services.Contracts;
using StoreApp.Models;

namespace StoreApp.Controllers
{
    public class ProductController : Controller
    {
        private readonly IServiceManager _manager;
        public ProductController(IServiceManager manager)
        {
            _manager = manager;
        }

        public IActionResult Index(ProductRequestParameters p)
        {
            var products = _manager.ProductService.GetAllProductsWithDetails(p);
            var pagination = new Pagination()
            {
                CurrentPage = p.PageNumber,
                ItemsPerPage = p.PageSize,
                TotalItems = _manager.ProductService.GetAllProducts(false).Count()
            };
            var productlistViewModel = new ProductListViewModel(){
                Products = products,
                Pagination = pagination
            };
            return View(productlistViewModel);
        }
        public IActionResult Get([FromRoute(Name = "id")] int id)
        {
            var product = _manager.ProductService.GetOneProduct(id, false);
            return View(product);
        }
    }
}

StoreApp/Views/Shared/_Footer.cshtml
<div class="border-top p-3">
    <div class="container">
        <div class="row">
            <div class="col-md-2">
                <div class="lead text-center">
                    <i class="fa-solid fa-store text-secondary display-6"></i>
                    <br>
                    <bold>BTK</bold>Akademi
                </div>
                <div class="text-muted text-center">
                    Store App
                </div>
            </div>
            <div class="col-md-8">
                <div class="text-center text-muted my-3">
                    &copy; 2023 <br> BTK Akademi ASP.NET Core MVC Kursu
                </div>
            </div>
            <div class="col-md-2">
                <div products="" number="6"> </div>

            </div>
        </div>
    </div>
</div>

StoreApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Store</title>
    <link asp-append-version="true" rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css">
    <link asp-append-version="true" rel="stylesheet" href="~/css/site.css">
    <link asp-append-version="true" rel="stylesheet" href="~/lib/font-awesome/css/all.css">
</head>

<body>
    <header>
        <partial name="_Navbar" />
        @RenderSection("Header",false)
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer>
        @RenderSection("Footer",false)
        <partial name="_Footer" />
    </footer>
    <script asp-append-version="true" src="~/lib/jquery/jquery.min.js"></script>
    <script asp-append-version="true" src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script asp-append-version="true" src="~/lib/font-awesome/js/all.min.js"></script>
    <script asp-append-version="true" src="~/scripts/site.js"></script>
    @await RenderSectionAsync("Scripts", required:false)
</body>

</html>

StoreApp/Views/Shared/_LoginMenu.cshtml
@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
    <li class="nav-item">
        <a class="nav-link" asp-area="Admin" asp-controller="Dashboard" asp-action="Index">
            <i class="fa-solid fa-user-pen"></i>
            Admin
            </a>
    </li>
}

@if (User.Identity.IsAuthenticated)
{
    <li class="nav-item">
        <a class="nav-link" 
        asp-area="" 
        asp-controller="Account" 
        asp-action="Logout"
        asp-route-returnUrl="@Context.Request.PathAndQuery()">
        <i class="fa-solid fa-right-from-bracket"></i>
        Logout
        </a>
    </li>
}
else
{
    <li class="nav-item">
        <a class="nav-link" 
        asp-area="" 
        asp-controller="Account" 
        asp-action="Login"
        asp-route-returnUrl="@Context.Request.PathAndQuery()">
        <i class="fa-solid fa-right-to-bracket"></i>&nbsp;
        Login
        </a>
    </li>
}

StoreApp/Views/Shared/_Navbar.cshtml
<nav class="navbar bg-primary border-bottom navbar-expand-lg bg-body-tertiary">
    <div class="container">
        <a class="navbar-brand">
            <i class="fa-solid fa-store fa-xl"></i>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" asp-controller="Home" asp-action="Index">
                        Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Product" asp-action="Index">
                        Product (@await Component.InvokeAsync("ProductSummary"))</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Category" asp-action="Index">Categories</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-page="/Contact">Contact</a>
                </li>
            </ul>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-page="/Cart">
                        <i class="fa-solid fa-cart-shopping"></i>
                        (@await Component.InvokeAsync("CartSummary"))
                    </a>
                </li>
               
                <partial name="_LoginMenu"/>
            </ul>
        </div>
    </div>
</nav>

StoreApp/Views/Shared/_Notification.cshtml
@if (TempData["info"] is not null)
{
    <div class="alert alert-info my-3" role="alert">
        @TempData["info"]
    </div>
}

@if (TempData["success"] is not null)
{
    <div class="alert alert-success my-3" role="alert">
        @TempData["success"]
    </div>
}

@if (TempData["danger"] is not null)
{
    <div class="alert alert-danger my-3" role="alert">
        @TempData["danger"]
    </div>
}

StoreApp/Views/Shared/_ProductCart.cshtml
@model Product

<div class="col-md-4 my-3">
    <div class="card" style="width: 18rem;">
        <div class="card-header text-center">
            @Model.ProductName
        </div>
        <img src="@Model?.ImageUrl" height="250" class="card-img-top" alt="...">
        <div class="card-body">
            <p class="card-text">@Model.Summary</p>
            <p class="card-text">@Model.Price.ToString("C")</p>
            <div class="d-flex justify-content-center">
                <div class="btn-group">
                    <a asp-controller="Product" asp-action="Get" asp-route-id="@Model.ProductId"
                        class="btn btn-primary rounded-2">
                        <i class="fa-solid fa-arrow-right"></i>&nbsp;Details</a>

                    <form id="@Model.ProductId" asp-page="/cart" method="post">

                        <input type="hidden" asp-for="ProductId">
                        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()">

                        <button class="btn btn-outline-success mx-2" type="submit">
                            <i class="fa-solid fa-cart-plus"></i>
                        </button>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>